FROM jhonacevedo/sonar-scanner-image AS sonarqube_scan
WORKDIR /app
COPY . .
# RUN
RUN sonar-scanner \
    -Dsonar.host.url="http://localhost:9000" \
    -Dsonar.projectKey="Elite" \
    -Dsonar.sources="/app/elite/frontend"
